# Generated by Django 4.2.5 on 2023-10-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='department',
            field=models.CharField(default='IT', max_length=300),
        ),
        migrations.AddField(
            model_name='data',
            name='dp',
            field=models.ImageField(default='media/blank.PNG', upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='data',
            name='experience',
            field=models.CharField(default='Fresher', max_length=300),
        ),
        migrations.AddField(
            model_name='data',
            name='role',
            field=models.CharField(default='developer', max_length=300),
        ),
        migrations.AddField(
            model_name='data',
            name='salary',
            field=models.IntegerField(default=100000),
        ),
    ]
