# Generated by Django 4.2.5 on 2023-10-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_data_department_data_dp_data_experience_data_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dp',
            field=models.ImageField(default='dp/blank.png', upload_to='dp/'),
        ),
    ]
